theme: jekyll-theme-cayman

# Themes are encouraged to use these universal variables
# so be sure to set them if your theme uses them.
#
title : blog
author :
  name : Jaroslav Bezdek
  email : bezdekjarda@seznam.cz
  github : Sasanka20

# NOTE: Replacing this next line with your own URL
production_url : https://sasanka20.github.io/blog/
